In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('../data/raw/Dataset.csv')

In [4]:
df['Patient_ID'].unique().shape

(14058,)

In [5]:
df1=df.copy()

In [6]:
df1=df1.groupby('Patient_ID')

In [7]:
df1.head()

,Unnamed: 0,Hour,HR,O2Sat,Temp,SBP,MAP,DBP,Resp,EtCO2,...,Fibrinogen,Platelets,Age,Gender,Unit1,Unit2,HospAdmTime,ICULOS,SepsisLabel,Patient_ID
0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,68.54,0.0,NaN,NaN,-0.02,1.0,0.0,17072.0
1,1,1,65.0,100.0,NaN,NaN,72.0,NaN,16.5,NaN,...,NaN,NaN,68.54,0.0,NaN,NaN,-0.02,2.0,0.0,17072.0
2,2,2,78.0,100.0,NaN,NaN,42.5,NaN,NaN,NaN,...,NaN,NaN,68.54,0.0,NaN,NaN,-0.02,3.0,0.0,17072.0
3,3,3,73.0,100.0,NaN,NaN,NaN,NaN,17.0,NaN,...,NaN,NaN,68.54,0.0,NaN,NaN,-0.02,4.0,0.0,17072.0
4,4,4,70.0,100.0,NaN,129.0,74.0,69.0,14.0,NaN,...,NaN,330.0,68.54,0.0,NaN,NaN,-0.02,5.0,0.0,17072.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
546095,0,0,106.0,97.0,NaN,NaN,77.0,NaN,23.0,NaN,...,NaN,NaN,70.93,1.0,1.0,0.0,-313.53,3.0,0.0,2314.0
546096,1,1,103.0,99.0,36.78,NaN,81.0,NaN,20.0,NaN,...,NaN,NaN,70.93,1.0,1.0,0.0,-313.53,4.0,0.0,2314.0
546097,2,2,108.0,97.0,NaN,NaN,88.0,NaN,24.0,NaN,...,NaN,NaN,70.93,1.0,1.0,0.0,-313.53,5.0,0.0,2314.0
546098,3,3,102.0,97.0,NaN,NaN,46.0,NaN,24.0,NaN,...,NaN,NaN,70.93,1.0,1.0,0.0,-313.53,6.0,0.0,2314.0
546099,4,4,102.0,97.0,NaN,NaN,62.0,NaN,26.0,NaN,...,NaN,NaN,70.93,1.0,1.0,0.0,-313.53,7.0,0.0,2314.0

In [8]:
df = df.set_index(['Patient_ID','ICULOS'])

In [9]:
df.head()

                   Unnamed: 0  Hour    HR  O2Sat  Temp    SBP   MAP   DBP  \
Patient_ID ICULOS
17072.0    1.0              0     0   NaN    NaN   NaN    NaN   NaN   NaN
           2.0              1     1  65.0  100.0   NaN    NaN  72.0   NaN
           3.0              2     2  78.0  100.0   NaN    NaN  42.5   NaN
           4.0              3     3  73.0  100.0   NaN    NaN   NaN   NaN
           5.0              4     4  70.0  100.0   NaN  129.0  74.0  69.0

                   Resp  EtCO2  ...   PTT   WBC  Fibrinogen  Platelets    Age  \
Patient_ID ICULOS               ...
17072.0    1.0      NaN    NaN  ...   NaN   NaN         NaN        NaN  68.54
           2.0     16.5    NaN  ...   NaN   NaN         NaN        NaN  68.54
           3.0      NaN    NaN  ...   NaN   NaN         NaN        NaN  68.54
           4.0     17.0    NaN  ...   NaN   NaN         NaN        NaN  68.54
           5.0     14.0    NaN  ...  30.6  11.3         NaN      330.0  68.54

                   Gender  Unit1  Unit2  HospAdmTime  SepsisLabel
Patient_ID ICULOS
17072.0    1.0        0.0    NaN    NaN        -0.02          0.0
           2.0        0.0    NaN    NaN        -0.02          0.0
           3.0        0.0    NaN    NaN        -0.02          0.0
           4.0        0.0    NaN    NaN        -0.02          0.0
           5.0        0.0    NaN    NaN        -0.02          0.0

[5 rows x 42 columns]

In [10]:
df.columns

Index(['Unnamed: 0', 'Hour', 'HR', 'O2Sat', 'Temp', 'SBP', 'MAP', 'DBP',
       'Resp', 'EtCO2', 'BaseExcess', 'HCO3', 'FiO2', 'pH', 'PaCO2', 'SaO2',
       'AST', 'BUN', 'Alkalinephos', 'Calcium', 'Chloride', 'Creatinine',
       'Bilirubin_direct', 'Glucose', 'Lactate', 'Magnesium', 'Phosphate',
       'Potassium', 'Bilirubin_total', 'TroponinI', 'Hct', 'Hgb', 'PTT', 'WBC',
       'Fibrinogen', 'Platelets', 'Age', 'Gender', 'Unit1', 'Unit2',
       'HospAdmTime', 'SepsisLabel'],
      dtype='str')

In [11]:
un_wanted_column=['Unit1', 'Unit2', 'HospAdmTime', 'Unnamed: 0']
df=df.drop(columns=un_wanted_column)

In [12]:
df.head(20)

                   Hour    HR  O2Sat   Temp    SBP   MAP   DBP  Resp  EtCO2  \
Patient_ID ICULOS
17072.0    1.0        0   NaN    NaN    NaN    NaN   NaN   NaN   NaN    NaN
           2.0        1  65.0  100.0    NaN    NaN  72.0   NaN  16.5    NaN
           3.0        2  78.0  100.0    NaN    NaN  42.5   NaN   NaN    NaN
           4.0        3  73.0  100.0    NaN    NaN   NaN   NaN  17.0    NaN
           5.0        4  70.0  100.0    NaN  129.0  74.0  69.0  14.0    NaN
           6.0        5  62.0  100.0    NaN  124.0  85.0  61.0  14.0    NaN
           7.0        6  61.0  100.0    NaN  101.0  75.0  58.0  14.0    NaN
           8.0        7  68.0  100.0  35.78  142.0  93.5  78.0  16.0    NaN
           9.0        8  71.0  100.0    NaN  121.0  74.0  91.0  14.0    NaN
           10.0       9  69.0  100.0    NaN  120.0  79.0  98.0  14.0    NaN
           11.0      10  75.0  100.0    NaN  146.0  93.0  67.0  14.0    NaN
           12.0      11  84.0  100.0  36.39  128.0  80.0  60.0  14.0    NaN
           13.0      12  85.0  100.0    NaN  124.0  79.0  59.0  14.0    NaN
           14.0      13  85.0  100.0    NaN  141.0  95.0  69.0  14.0    NaN
           15.0      14  89.0  100.0    NaN  117.0  86.0  68.0  14.0    NaN
           16.0      15  88.0  100.0    NaN  121.0  86.0  66.0  14.0    NaN
           17.0      16  89.0  100.0  37.50  112.0  82.5  63.0  14.0    NaN
           18.0      17  89.0  100.0    NaN  130.0  99.0  76.0  14.0    NaN
           19.0      18  86.0  100.0    NaN  114.0  96.0  86.0  14.0    NaN
           20.0      19  83.0  100.0  37.22  115.0  97.0  85.0  14.0    NaN

                   BaseExcess  ...  TroponinI   Hct   Hgb   PTT   WBC  \
Patient_ID ICULOS              ...
17072.0    1.0            NaN  ...        NaN   NaN   NaN   NaN   NaN
           2.0            NaN  ...        NaN   NaN   NaN   NaN   NaN
           3.0            NaN  ...        NaN   NaN   NaN   NaN   NaN
           4.0            NaN  ...        NaN   NaN   NaN   NaN   NaN
           5.0            NaN  ...        NaN  29.7   9.5  30.6  11.3
           6.0            6.0  ...        NaN   NaN   NaN   NaN   NaN
           7.0            NaN  ...        NaN   NaN   NaN   NaN   NaN
           8.0            NaN  ...        NaN   NaN   NaN   NaN   NaN
           9.0            3.0  ...        NaN   NaN   NaN   NaN   NaN
           10.0           NaN  ...        NaN   NaN   NaN   NaN   NaN
           11.0           NaN  ...        NaN   NaN   NaN   NaN   NaN
           12.0           NaN  ...        NaN   NaN   NaN   NaN   NaN
           13.0           NaN  ...        NaN   NaN   NaN   NaN   NaN
           14.0           NaN  ...        NaN  30.2  10.0   NaN  11.0
           15.0           NaN  ...        NaN   NaN   NaN   NaN   NaN
           16.0           NaN  ...        NaN   NaN   NaN   NaN   NaN
           17.0           NaN  ...        NaN   NaN   NaN   NaN   NaN
           18.0           NaN  ...        NaN   NaN   NaN   NaN   NaN
           19.0           NaN  ...        NaN   NaN   NaN   NaN   NaN
           20.0           NaN  ...        NaN   NaN   NaN   NaN   NaN

                   Fibrinogen  Platelets    Age  Gender  SepsisLabel
Patient_ID ICULOS
17072.0    1.0            NaN        NaN  68.54     0.0          0.0
           2.0            NaN        NaN  68.54     0.0          0.0
           3.0            NaN        NaN  68.54     0.0          0.0
           4.0            NaN        NaN  68.54     0.0          0.0
           5.0            NaN      330.0  68.54     0.0          0.0
           6.0            NaN        NaN  68.54     0.0          0.0
           7.0            NaN        NaN  68.54     0.0          0.0
           8.0            NaN        NaN  68.54     0.0          0.0
           9.0            NaN        NaN  68.54     0.0          0.0
           10.0           NaN        NaN  68.54     0.0          0.0
           11.0           NaN        NaN  68.54     0.0          0.0
           12.0           NaN        NaN  68.54     0.0          0.0
           13.0           NaN        NaN  68.54     0.0          0.0
           14.0           NaN      303.0  68.54     0.0          0.0
           15.0           NaN        NaN  68.54     0.0          0.0
           16.0           NaN        NaN  68.54     0.0          0.0
           17.0           NaN        NaN  68.54     0.0          0.0
           18.0           NaN        NaN  68.54     0.0          0.0
           19.0           NaN        NaN  68.54     0.0          0.0
           20.0           NaN        NaN  68.54     0.0          0.0

[20 rows x 38 columns]

In [13]:
df['Spesis_onset']=df.groupby('Patient_ID')['SepsisLabel'].diff()

In [14]:
df.head()

                   Hour    HR  O2Sat  Temp    SBP   MAP   DBP  Resp  EtCO2  \
Patient_ID ICULOS
17072.0    1.0        0   NaN    NaN   NaN    NaN   NaN   NaN   NaN    NaN
           2.0        1  65.0  100.0   NaN    NaN  72.0   NaN  16.5    NaN
           3.0        2  78.0  100.0   NaN    NaN  42.5   NaN   NaN    NaN
           4.0        3  73.0  100.0   NaN    NaN   NaN   NaN  17.0    NaN
           5.0        4  70.0  100.0   NaN  129.0  74.0  69.0  14.0    NaN

                   BaseExcess  ...   Hct  Hgb   PTT   WBC  Fibrinogen  \
Patient_ID ICULOS              ...
17072.0    1.0            NaN  ...   NaN  NaN   NaN   NaN         NaN
           2.0            NaN  ...   NaN  NaN   NaN   NaN         NaN
           3.0            NaN  ...   NaN  NaN   NaN   NaN         NaN
           4.0            NaN  ...   NaN  NaN   NaN   NaN         NaN
           5.0            NaN  ...  29.7  9.5  30.6  11.3         NaN

                   Platelets    Age  Gender  SepsisLabel  Spesis_onset
Patient_ID ICULOS
17072.0    1.0           NaN  68.54     0.0          0.0           NaN
           2.0           NaN  68.54     0.0          0.0           0.0
           3.0           NaN  68.54     0.0          0.0           0.0
           4.0           NaN  68.54     0.0          0.0           0.0
           5.0         330.0  68.54     0.0          0.0           0.0

[5 rows x 39 columns]

In [15]:
df[df['SepsisLabel']==1].head(20)

                   Hour     HR  O2Sat   Temp    SBP   MAP   DBP  Resp  EtCO2  \
Patient_ID ICULOS
11093.0    53.0      50   87.0  100.0    NaN  105.0  65.0  67.0  19.0    NaN
           54.0      51   93.0  100.0    NaN   94.0  72.0  56.0  18.0    NaN
           55.0      52   95.0  100.0    NaN  110.0  80.0  90.0  13.0    NaN
           56.0      53   94.0  100.0    NaN   95.0  74.0  58.0  20.0    NaN
           57.0      54   94.0  100.0    NaN   95.0  73.0  58.0  22.0    NaN
           58.0      55   97.0  100.0    NaN   96.0  75.0  60.0  13.0    NaN
           59.0      56   99.0  100.0    NaN  102.0  79.0  63.0  15.0    NaN
           60.0      57   94.0  100.0    NaN   84.0  62.0  53.0  17.0    NaN
           61.0      58   97.0  100.0    NaN   87.0  79.0  69.0  23.0    NaN
           62.0      59   96.0  100.0    NaN   76.0  65.0  55.0  16.0    NaN
10355.0    67.0      66   97.0   95.0  36.50  101.0  66.0  50.0  31.5    NaN
           68.0      67  113.0   94.0    NaN   97.0  68.0  55.0  30.0    NaN
           69.0      68  115.0   95.5  36.36   91.5  66.0  53.5  31.5    NaN
           70.0      69  112.0   97.0  35.89  108.0  78.0  61.0  32.0    NaN
           71.0      70  118.5   97.5  36.28   88.5  64.0  52.0  30.5    NaN
           72.0      71  112.0   97.5    NaN   79.5  58.0  48.0  31.5    NaN
           73.0      72  115.0   96.0    NaN   86.0  62.0  49.0  31.0    NaN
           74.0      73  109.0   96.0    NaN   91.0  64.0  50.0  28.0    NaN
           75.0      74  113.0   97.0  36.72   75.0  58.0  48.0  31.0    NaN
           76.0      75  117.0   97.0    NaN   89.0  68.0  55.5  32.0    NaN

                   BaseExcess  ...   Hct   Hgb  PTT  WBC  Fibrinogen  \
Patient_ID ICULOS              ...
11093.0    53.0           NaN  ...   NaN   NaN  NaN  NaN         NaN
           54.0           NaN  ...   NaN   NaN  NaN  NaN         NaN
           55.0           NaN  ...   NaN   NaN  NaN  NaN         NaN
           56.0           NaN  ...   NaN   NaN  NaN  NaN         NaN
           57.0           NaN  ...   NaN   NaN  NaN  NaN         NaN
           58.0           NaN  ...  36.6  13.0  NaN  8.9         NaN
           59.0           NaN  ...  36.6  13.0  NaN  8.9         NaN
           60.0           NaN  ...   NaN   NaN  NaN  NaN         NaN
           61.0           NaN  ...   NaN   NaN  NaN  NaN         NaN
           62.0           NaN  ...   NaN   NaN  NaN  NaN         NaN
10355.0    67.0           NaN  ...   NaN   NaN  NaN  NaN         NaN
           68.0           NaN  ...   NaN   NaN  NaN  NaN         NaN
           69.0           NaN  ...   NaN   NaN  NaN  NaN         NaN
           70.0           NaN  ...   NaN   NaN  NaN  NaN         NaN
           71.0           NaN  ...   NaN   NaN  NaN  NaN         NaN
           72.0           NaN  ...   NaN   NaN  NaN  NaN         NaN
           73.0           NaN  ...   NaN   NaN  NaN  NaN         NaN
           74.0           NaN  ...   NaN   NaN  NaN  NaN         NaN
           75.0           NaN  ...   NaN   NaN  NaN  NaN         NaN
           76.0          -8.0  ...   NaN   NaN  NaN  NaN         NaN

                   Platelets    Age  Gender  SepsisLabel  Spesis_onset
Patient_ID ICULOS
11093.0    53.0          NaN  59.28     1.0          1.0           1.0
           54.0          NaN  59.28     1.0          1.0           0.0
           55.0          NaN  59.28     1.0          1.0           0.0
           56.0          NaN  59.28     1.0          1.0           0.0
           57.0          NaN  59.28     1.0          1.0           0.0
           58.0        134.0  59.28     1.0          1.0           0.0
           59.0          NaN  59.28     1.0          1.0           0.0
           60.0          NaN  59.28     1.0          1.0           0.0
           61.0          NaN  59.28     1.0          1.0           0.0
           62.0          NaN  59.28     1.0          1.0           0.0
10355.0    67.0          NaN  86.26     1.0          1.0           1.0
           68.0          NaN  86.26     1.0          1.0           0.0
           69.0          NaN  86.26     1.0          1.0           0.0
           70.0          NaN  86.26     1.0          1.0           0.0
           71.0         62.0  86.26     1.0          1.0           0.0
           72.0          NaN  86.26     1.0          1.0           0.0
           73.0          NaN  86.26     1.0          1.0           0.0
           74.0          NaN  86.26     1.0          1.0           0.0
           75.0          NaN  86.26     1.0          1.0           0.0
           76.0          NaN  86.26     1.0          1.0           0.0

[20 rows x 39 columns]

In [19]:
df.head(40)['Hour']

Patient_ID  ICULOS
17072.0     1.0        0
            2.0        1
            3.0        2
            4.0        3
            5.0        4
            6.0        5
            7.0        6
            8.0        7
            9.0        8
            10.0       9
            11.0      10
            12.0      11
            13.0      12
            14.0      13
            15.0      14
            16.0      15
            17.0      16
            18.0      17
            19.0      18
            20.0      19
            21.0      20
            22.0      21
            23.0      22
            24.0      23
            25.0      24
            26.0      25
            27.0      26
            28.0      27
            29.0      28
            30.0      29
            31.0      30
            32.0      31
            33.0      32
            34.0      33
            35.0      34
            36.0      35
            37.0      36
            38.0      37
            39.0      38
            40.0      39
Name: Hour, dtype: int64

In [20]:
# بنعمل ميزة جديدة اسمها 'True_Hour' عشان نعرف الساعة كام في اليوم بالظبط
df['True_Hour'] = df['Hour'] % 24

In [23]:
df['True_Hour'].head(40)

Patient_ID  ICULOS
17072.0     1.0        0
            2.0        1
            3.0        2
            4.0        3
            5.0        4
            6.0        5
            7.0        6
            8.0        7
            9.0        8
            10.0       9
            11.0      10
            12.0      11
            13.0      12
            14.0      13
            15.0      14
            16.0      15
            17.0      16
            18.0      17
            19.0      18
            20.0      19
            21.0      20
            22.0      21
            23.0      22
            24.0      23
            25.0       0
            26.0       1
            27.0       2
            28.0       3
            29.0       4
            30.0       5
            31.0       6
            32.0       7
            33.0       8
            34.0       9
            35.0      10
            36.0      11
            37.0      12
            38.0      13
            39.0      14
            40.0      15
Name: True_Hour, dtype: int64